platform :ios, '12.0'

target 'Runner' do
  use_frameworks!  # Ensure dynamic frameworks are enabled
  use_modular_headers!

  # Fix for connectivity_plus and other dependencies
  pod 'connectivity_plus', :modular_headers => true
  pod 'DKPhotoGallery', :modular_headers => true
  pod 'SDWebImage', :modular_headers => true

  # Additional dependencies can be added here if needed
  
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
