platform :ios, '12.0'

# Set the correct path to your Flutter SDK directory
# Load Flutter environment
flutter_root = File.expand_path('..', Dir.pwd) + '/flutter'
load File.join(flutter_root, 'flutter_export_environment.rb') if File.exist?(File.join(flutter_root, 'flutter_export_environment.rb'))

flutter_application_path = '../..'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Add Flutter as a pod
  pod 'Flutter', :path => flutter_root

  # Your other dependencies
  pod 'DKPhotoGallery', :modular_headers => true
  pod 'SDWebImage', :modular_headers => true

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
