platform :ios, '12.0'

target 'Runner' do
  # Use modular headers to prevent conflicts
  use_modular_headers!

  # Pods for Runner
  pod 'DKPhotoGallery'
  pod 'SDWebImage'

  # Ensure Flipper is disabled if not needed
  # use_flipper!({ 'Flipper' => '0.125.0' })  # Uncomment if needed

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
