name: Build iOS IPA

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: macOS-latest  # Use a macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out your repository

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Set up Flutter
        with:
          channel: stable  # Use the stable Flutter channel

      - name: Install dependencies
        run: flutter pub get  # Install Flutter dependencies

      - name: Build IPA
        run: flutter build ipa --release  # Build the IPA

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v3  # Upload the IPA as a build artifact
        with:
          name: app-release.ipa
          path: build/ios/ipa/app-release.ipa
